site:
  title: Pholio Rails
  tagline: A photographic portfolio site in Ruby on Rails
disqus:
  shortname: localdev-kalleth
static_pages:
  - title: Contact
    slug: contact
  - title: Imprint
    slug: imprint
